use project_3;
insert into users (name, email, password, createdAt, updatedAt) values ('new user 1', 'user1email@newuser.com', 'user1password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 2', 'user2email@newuser.com', 'user2password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 3', 'user3email@newuser.com', 'user3password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 4', 'user4email@newuser.com', 'user4password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 5', 'user5email@newuser.com', 'user5password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 6', 'user6email@newuser.com', 'user6password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 7', 'user7email@newuser.com', 'user7password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 8', 'user8email@newuser.com', 'user8password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 9', 'user9email@newuser.com', 'user9password', current_timestamp(), current_timestamp());

insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink1.com", current_timestamp(), current_timestamp(), 1);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink2.com", current_timestamp(), current_timestamp(), 1);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink3.com", current_timestamp(), current_timestamp(), 1);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink4.com", current_timestamp(), current_timestamp(), 1);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink5.com", current_timestamp(), current_timestamp(), 2);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink6.com", current_timestamp(), current_timestamp(), 2);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink7.com", current_timestamp(), current_timestamp(), 2);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink8.com", current_timestamp(), current_timestamp(), 2);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink9.com", current_timestamp(), current_timestamp(), 2);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink10.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink11.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink12.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink13.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink14.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink15.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink16.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink17.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink18.com", current_timestamp(), current_timestamp(), 3);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink19.com", current_timestamp(), current_timestamp(), 4);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink20.com", current_timestamp(), current_timestamp(), 4);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink21.com", current_timestamp(), current_timestamp(), 4);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink22.com", current_timestamp(), current_timestamp(), 5);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink23.com", current_timestamp(), current_timestamp(), 5);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink24.com", current_timestamp(), current_timestamp(), 6);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink25.com", current_timestamp(), current_timestamp(), 6);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink26.com", current_timestamp(), current_timestamp(), 6);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink27.com", current_timestamp(), current_timestamp(), 7);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink28.com", current_timestamp(), current_timestamp(), 8);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink29.com", current_timestamp(), current_timestamp(), 8);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink30.com", current_timestamp(), current_timestamp(), 8);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink31.com", current_timestamp(), current_timestamp(), 9);
insert into favorites (videoUrl, createdAt, updatedAt, UserId) values ("www.videolink32.com", current_timestamp(), current_timestamp(), 9);