use project_3;

insert into users (name, email, password, createdAt, updatedAt) values ('new user 1', 'user1email@newuser.com', 'user1password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 2', 'user2email@newuser.com', 'user2password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 3', 'user3email@newuser.com', 'user3password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 4', 'user4email@newuser.com', 'user4password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 5', 'user5email@newuser.com', 'user5password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 6', 'user6email@newuser.com', 'user6password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 7', 'user7email@newuser.com', 'user7password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 8', 'user8email@newuser.com', 'user8password', current_timestamp(), current_timestamp());
insert into users (name, email, password, createdAt, updatedAt) values ('new user 9', 'user9email@newuser.com', 'user9password', current_timestamp(), current_timestamp());

insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink1.com", 'video', current_timestamp(), current_timestamp(), 1);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink2.com", 'audio', current_timestamp(), current_timestamp(), 1);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink3.com", 'image', current_timestamp(), current_timestamp(), 1);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink4.com", 'image', current_timestamp(), current_timestamp(), 1);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink5.com", 'audio', current_timestamp(), current_timestamp(), 2);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink6.com", 'audio', current_timestamp(), current_timestamp(), 2);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink7.com", 'video', current_timestamp(), current_timestamp(), 2);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink8.com", 'image', current_timestamp(), current_timestamp(), 2);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink9.com", 'video', current_timestamp(), current_timestamp(), 2);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink10.com", 'video', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink11.com", 'audio', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink12.com", 'image', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink13.com", 'image', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink14.com", 'image', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink15.com", 'image', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink16.com", 'image', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink17.com", 'video', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink18.com", 'image', current_timestamp(), current_timestamp(), 3);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink19.com", 'video', current_timestamp(), current_timestamp(), 4);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink20.com", 'video', current_timestamp(), current_timestamp(), 4);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink21.com", 'video', current_timestamp(), current_timestamp(), 4);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink22.com", 'audio', current_timestamp(), current_timestamp(), 5);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink23.com", 'image', current_timestamp(), current_timestamp(), 5);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink24.com", 'audio', current_timestamp(), current_timestamp(), 6);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink25.com", 'audio', current_timestamp(), current_timestamp(), 6);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink26.com", 'audio', current_timestamp(), current_timestamp(), 6);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink27.com", 'image', current_timestamp(), current_timestamp(), 7);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink28.com", 'image', current_timestamp(), current_timestamp(), 8);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink29.com", 'video', current_timestamp(), current_timestamp(), 8);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink30.com", 'video', current_timestamp(), current_timestamp(), 8);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink31.com", 'image', current_timestamp(), current_timestamp(), 9);
insert into favorites (url, media_type, createdAt, updatedAt, UserId) values ("www.medialink32.com", 'image', current_timestamp(), current_timestamp(), 9);